backend:
  host: "localhost"   
  port: "52709"        

kafka:
  host: "localhost"   
  port: "9092"       
  topic: "product-queries"

server:
  port: "8084"

management:
  endpoints:
    web:
      exposure:
        include: "*"



