backend:
  host: "localhost"   
  port: "8090"        
  api: "http://${backend.host}:${backend.port}"  

kafka:
  host: "localhost"   
  port: "9092"       
  topic: "product-queries"
  bootstrap-servers: "${kafka.host}:${kafka.port}"  

server:
  port: "8080"

management:
  endpoints:
    web:
      exposure:
        include: "*"



